# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
	  build:
	    docker:
      		- image: cibuilds/hugo:latest
   		working_directory: ~/hugo
    	environment:
      		HUGO_BUILD_DIR: ~/hugo/public
    	steps:
	    	# install git
      		- run: apk update && apk add git

      		# checkout the repository
      		- checkout

      		# install git submodules for managing third-party dependencies
      		- run: git submodule sync && git submodule update --init

      		- run:
          		name: install AWS CLI (first install pip, the Python package manager)
          		command: |
            		apk add --update python python-dev py-pip build-base
            		pip install awscli

      		# build with Hugo
      		- run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
 
      		- run:
          		name: test our generated HTML files
          		command: |
            		htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            		--empty-alt-ignore --disable-external

      		# `deploy` step: identical to a `run` step, but uses only one container:
      		# /docs/2.0/configuration-reference/#deploy 
      		- deploy:
          		name: deploy to AWS
          		command: |
            		if [ "${CIRCLE_BRANCH}" = "master" ]; then
              			aws s3 sync $HUGO_BUILD_DIR \
              			s3://my-static-site --delete
            		else
              			echo "Not master branch, dry run only"
            		fi